# Generated by Django 4.2.3 on 2023-07-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='quota',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
