# Generated by Django 4.2.4 on 2023-08-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
