# Generated by Django 4.2.3 on 2023-07-06 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 19, 31, 40, 4748, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
