# Generated by Django 4.2.3 on 2023-07-09 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='recipt_no',
            new_name='student',
        ),
    ]
