# Generated by Django 4.2.3 on 2023-07-09 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_student_admission_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='docs_ver',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stud_ver',
        ),
        migrations.AddField(
            model_name='student',
            name='version_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_count', models.IntegerField()),
                ('docs_ver', models.IntegerField()),
                ('stud_ver', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.student')),
            ],
        ),
    ]
