# Generated by Django 4.2.3 on 2023-07-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_student_docs_ver_remove_student_stud_ver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lock',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
