version: '3'


services:

  # njinx:
  #   build: ./njinx/
  #   restart: always
  #   container_name: njinx
  #   volumes:
  #     - ./static:/static/

  #   ports:
  #     - "80:8000"

  #   depends_on:
  #     - site

  #   networks:
  #     - kgcar

  # site:

  #   build: .
  #   container_name: doc-portal-server
  
  #   restart: always
  #   volumes:
  #     - .:/app
    
  #   ports:
  #     - "8000:8000"

  #   networks:
  #     - kgcar

  db:

    image: mysql
    container_name: doc-portal-db
    restart: always

    ports:
      - "5500:3306"

    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: doc-db
      MYSQL_USER: user
      MYSQL_PASSWORD: doc-viewer
    
    volumes:
      - storage:/var/lib/mysql
    
    networks:
      - kgcar

volumes:
  storage:
    name: "doc-portal-data"


networks:
  kgcar:
    driver: bridge